package com.eos.ui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.GraphicsDevice;
import java.awt.Window;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;

import com.eos.dao.BaiHocDAO;
import com.eos.dao.ChuongDAO;
import com.eos.model.BaiHoc;
import com.eos.model.Chuong;
import com.eos.untils.MsgBox;

import chrriis.dj.nativeswing.swtimpl.NativeInterface;
import chrriis.dj.nativeswing.swtimpl.components.JWebBrowser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class HocOnlineJDialog extends JFrame {

	/**
	 * Creates new form HocOnlineJDialog
	 */
	ChuongDAO cdao = new ChuongDAO();
	BaiHocDAO bhdao = new BaiHocDAO();
	JWebBrowser webBrowser;
	private GraphicsDevice device;
	private boolean fullScreen = false;
	private Container previousContentPane;
	int maKH;

	public HocOnlineJDialog() {
		initComponents();
		init();
		getContentPane().setBackground(Color.white);
		this.fillComboboxChuong();
	}

	public HocOnlineJDialog(int maKH) {
		initComponents();
		init();
		getContentPane().setBackground(Color.white);
		this.maKH = maKH;
		this.fillComboboxChuong();
	}

	public HocOnlineJDialog(String testing) {

	}

	private void init() {
		NativeInterface.open();
		webBrowser = new JWebBrowser(JWebBrowser.destroyOnFinalization());
		webBrowser.setBarsVisible(false);
		jInternalFrame2.putClientProperty("JInternalFrame.isPalette", Boolean.TRUE);
		jInternalFrame2.getRootPane().setWindowDecorationStyle(JRootPane.NONE);
		BasicInternalFrameUI bi = (BasicInternalFrameUI) jInternalFrame2.getUI();
		bi.setNorthPane(null);
		jInternalFrame2.setBorder(null);
		jInternalFrame2.add(webBrowser);
	}

	void fillComboboxChuong() {
		DefaultComboBoxModel model = (DefaultComboBoxModel) cboChuong.getModel();
		model.removeAllElements();
		try {
			List<Chuong> list = cdao.selectByKhoaHoc(maKH);
			for (Chuong c : list) {
				model.addElement(c);
			}
		} catch (Exception e) {
			MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
		}
	}
	public List<BaiHoc> fillComboboxChuong(Integer maKH) {
		try {
			List<Chuong> list = cdao.selectByKhoaHoc(maKH);
			List<BaiHoc> bh = bhdao.selectByKhoaHoc(list.get(0).getMaChuong());
			return bh;
		} catch (Exception e) {
			return null;
		}
	}

	void fillComboboxBaiHoc() {
		DefaultComboBoxModel model = (DefaultComboBoxModel) cboBaiHoc.getModel();
		model.removeAllElements();
		try {
			Chuong chuong = (Chuong) cboChuong.getSelectedItem();
			if (chuong != null) {
				List<BaiHoc> list = bhdao.selectByKhoaHoc(chuong.getMaChuong());
				for (BaiHoc c : list) {
					model.addElement(c);
				}
			}
		} catch (Exception e) {
			MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
		}
	}

	public List<BaiHoc> fillComboboxBaiHoc(Integer maChuong) {
		try {
			List<BaiHoc> list = bhdao.selectByKhoaHoc(maChuong);
			return list;

		} catch (Exception e) {
			return null;
		}
	}

	private void goFullScreen() {
		Window w = SwingUtilities.windowForComponent(webBrowser);
		if (w instanceof JFrame) {
			JFrame frame = (JFrame) w;
			frame.dispose();
			frame.getGraphicsConfiguration().getDevice().setFullScreenWindow(w);
			previousContentPane = frame.getContentPane();
			frame.setContentPane(webBrowser);
			frame.revalidate();
			frame.getContentPane().setLayout(new BorderLayout());
			frame.repaint();
			frame.setVisible(true);
			fullScreen = true;
		}
	}

	void edit() {
		BaiHoc bh = (BaiHoc) cboBaiHoc.getSelectedItem();
		if (bh != null) {
			List<BaiHoc> list = bhdao.selectByMaBaiHoc(bh.getMaBH());
			webBrowser.navigate(list.get(0).getLink());
		}
	}

	public List<BaiHoc> edit(Integer maBH) {
			List<BaiHoc> list = bhdao.selectByMaBaiHoc(maBH);
			return list;
	}

	private void ungoFullScreen() {
		Window w = SwingUtilities.windowForComponent(webBrowser);
		if (w instanceof JFrame) {
			JFrame frame = (JFrame) w;
			frame.dispose();
			frame.setUndecorated(false);
			frame.getGraphicsConfiguration().getDevice().setFullScreenWindow(null);
			frame.setContentPane(previousContentPane);

			jInternalFrame2.add(webBrowser);
			frame.revalidate();
			frame.repaint();
			frame.setVisible(true);
			fullScreen = false;
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jInternalFrame2 = new javax.swing.JInternalFrame();
		jPanel1 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		cboChuong = new javax.swing.JComboBox<>();
		jPanel5 = new javax.swing.JPanel();
		cboBaiHoc = new javax.swing.JComboBox<>();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("EOSys - Học online");

		jInternalFrame2.setVisible(true);
		jInternalFrame2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseEntered(java.awt.event.MouseEvent evt) {
				jInternalFrame2MouseEntered(evt);
			}
		});

		jPanel1.setLayout(new java.awt.GridLayout(1, 0));

		jPanel4.setBackground(new java.awt.Color(255, 255, 255));
		jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tên chương",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP,
				new java.awt.Font("Segoe UI", 0, 13))); // NOI18N
		jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

		cboChuong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
		cboChuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tin học" }));
		cboChuong.setFocusable(false);
		cboChuong.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cboChuongActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap()
						.addComponent(cboChuong, 0, 276, Short.MAX_VALUE).addContainerGap()));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addComponent(cboChuong,
						javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 9, Short.MAX_VALUE)));

		jPanel1.add(jPanel4);

		jPanel5.setBackground(new java.awt.Color(255, 255, 255));
		jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tên bài học",
				javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP,
				new java.awt.Font("Segoe UI", 0, 13))); // NOI18N
		jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

		cboBaiHoc.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
		cboBaiHoc.setModel(
				new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", " " }));
		cboBaiHoc.setFocusable(false);
		cboBaiHoc.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cboBaiHocActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout.setHorizontalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
						.addComponent(cboBaiHoc, 0, 276, Short.MAX_VALUE).addContainerGap()));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addComponent(cboBaiHoc,
						javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 9, Short.MAX_VALUE)));

		jPanel1.add(jPanel5);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jInternalFrame2)
						.addContainerGap())
				.addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, 0)
						.addComponent(jInternalFrame2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
						.addContainerGap()));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void cboChuongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cboChuongActionPerformed
		fillComboboxBaiHoc();
	}// GEN-LAST:event_cboChuongActionPerformed

	private void cboBaiHocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cboBaiHocActionPerformed
		this.edit();
	}// GEN-LAST:event_cboBaiHocActionPerformed

	private void jInternalFrame2MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jInternalFrame2MouseEntered

	}// GEN-LAST:event_jInternalFrame2MouseEntered

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(HocOnlineJDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(HocOnlineJDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(HocOnlineJDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(HocOnlineJDialog.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				HocOnlineJDialog dialog = new HocOnlineJDialog();
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox<String> cboBaiHoc;
	private javax.swing.JComboBox<String> cboChuong;
	private javax.swing.JInternalFrame jInternalFrame2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	// End of variables declaration//GEN-END:variables
}
