package com.eos.ui;

import com.eos.dao.KhoaHocDAO;
import com.eos.dao.KyThiDAO;
import com.eos.model.KhoaHoc;
import com.eos.model.KyThi;
import com.eos.untils.MsgBox;
import com.eos.untils.Auth;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Admin
 */
public class ThamGiaKyThiJDialog extends javax.swing.JDialog {

    /**
     * Creates new form ThamGiaKHJDialog
     */
    JFileChooser fileChooser = new JFileChooser();
    KyThiDAO ktdao = new KyThiDAO();
    KhoaHocDAO khdao = new KhoaHocDAO();
    int row = -1;

    public ThamGiaKyThiJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    public ThamGiaKyThiJDialog() {
		// TODO Auto-generated constructor stub
	}

	void init() {
        getRootPane().setOpaque(false);
        getContentPane().setBackground(Color.white);
        setBackground(Color.white);
        txtMaKT.requestFocus();
        btnTabDanhSach.doClick();
        tblKyThi.getTableHeader().setFont(new Font("Segoe UI", Font.PLAIN, 13));
        tblKyThi.getTableHeader().setForeground(Color.white);
        tblKyThi.getTableHeader().setOpaque(false);
        tblKyThi.getTableHeader().setBackground(new Color(0, 103, 192));
        tblKyThi.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.fillTable();
        canGiua();
    }

    void setForm(KyThi kt) {
        txtMaKT.setText(String.valueOf(kt.getMaKyThi()));
        KhoaHoc kh = khdao.selectById(kt.getMaKH());
        txtTenKH.setText(kh.getTenKH());
        txtTenKyThi.setText(kt.getTenKT());
        txtThoiGianLamBai.setText(String.valueOf(kt.getTGLamBai()));
    }

    void edit() {
        int maKT = (int) tblKyThi.getValueAt(this.row, 0);
        KyThi kt = ktdao.selectById(maKT);
        this.setForm(kt);
        btnTabCapNhat.doClick();
    }

    private String timKiemMatKhau(int maKT) {
        KyThi kt = ktdao.selectById(maKT);
        if (kt == null) {
            return null;
        } else {
            return kt.getMatKhau();
        }
    }

    void canGiua() {
        TableCellRenderer rendererFromHeader = tblKyThi.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tblKyThi.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tblKyThi.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tblKyThi.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tblKyThi.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblKyThi.getModel();
        model.setRowCount(0);
        try {
            List<KyThi> list = ktdao.selectAllJoinExam(Auth.user1.getMaND());
            for (KyThi kt : list) {
                KhoaHoc kh = khdao.selectById(kt.getMaKH());
                Object[] row = {kt.getMaKyThi(), kh.getTenKH(), kt.getTenKT(), kt.getTGLamBai()};
                model.addRow(row);
            }

        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTabCapNhat = new javax.swing.JButton();
        btnTabDanhSach = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTenCD = new javax.swing.JLabel();
        btnVaoThi = new javax.swing.JButton();
        lblThoiLuong = new javax.swing.JLabel();
        lblHocPhi = new javax.swing.JLabel();
        txtMaKT = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtTenKyThi = new javax.swing.JTextField();
        txtThoiGianLamBai = new javax.swing.JTextField();
        lblMaCD = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKyThi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EOSys - Tham gia kỳ thi");

        btnTabCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        btnTabCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTabCapNhat.setForeground(new java.awt.Color(177, 177, 177));
        btnTabCapNhat.setText("Tham gia");
        btnTabCapNhat.setBorder(null);
        btnTabCapNhat.setContentAreaFilled(false);
        btnTabCapNhat.setFocusable(false);
        btnTabCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabCapNhatActionPerformed(evt);
            }
        });

        btnTabDanhSach.setBackground(new java.awt.Color(255, 255, 255));
        btnTabDanhSach.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTabDanhSach.setForeground(new java.awt.Color(177, 177, 177));
        btnTabDanhSach.setText("Danh sách");
        btnTabDanhSach.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTabDanhSach.setContentAreaFilled(false);
        btnTabDanhSach.setFocusable(false);
        btnTabDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabDanhSachActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTenCD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblTenCD.setText("Tên khóa học");

        btnVaoThi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnVaoThi.setText("Vào thi");
        btnVaoThi.setFocusable(false);
        btnVaoThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaoThiActionPerformed(evt);
            }
        });

        lblThoiLuong.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblThoiLuong.setText("Thời gian làm bài");

        lblHocPhi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblHocPhi.setText("Tên kỳ thi");

        txtMaKT.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaKT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(177, 177, 177)));
        txtMaKT.setEnabled(false);
        txtMaKT.setOpaque(false);
        txtMaKT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMaKTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaKTFocusLost(evt);
            }
        });

        txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTenKH.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(177, 177, 177)));
        txtTenKH.setEnabled(false);
        txtTenKH.setOpaque(false);
        txtTenKH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenKHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenKHFocusLost(evt);
            }
        });

        txtTenKyThi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtTenKyThi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(177, 177, 177)));
        txtTenKyThi.setEnabled(false);
        txtTenKyThi.setOpaque(false);
        txtTenKyThi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTenKyThiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenKyThiFocusLost(evt);
            }
        });

        txtThoiGianLamBai.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtThoiGianLamBai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(177, 177, 177)));
        txtThoiGianLamBai.setEnabled(false);
        txtThoiGianLamBai.setOpaque(false);
        txtThoiGianLamBai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtThoiGianLamBaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtThoiGianLamBaiFocusLost(evt);
            }
        });

        lblMaCD.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblMaCD.setText("Mã kỳ thi");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 528, Short.MAX_VALUE)
                        .addComponent(btnVaoThi))
                    .addComponent(txtMaKT)
                    .addComponent(txtTenKH)
                    .addComponent(txtTenKyThi)
                    .addComponent(txtThoiGianLamBai)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThoiLuong)
                            .addComponent(lblMaCD)
                            .addComponent(lblHocPhi)
                            .addComponent(lblTenCD))
                        .addGap(0, 503, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMaCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaKT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblTenCD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHocPhi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenKyThi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThoiLuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtThoiGianLamBai, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVaoThi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, "card2");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tblKyThi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tblKyThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MÃ KT", "MÃ KH", "TÊN KT", "TG LÀM BÀI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKyThi.setGridColor(new java.awt.Color(177, 177, 177));
        tblKyThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKyThiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKyThi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTabDanhSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTabCapNhat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTabCapNhat)
                    .addComponent(btnTabDanhSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTabCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabCapNhatActionPerformed
        btnTabCapNhat.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 103, 192)),
                BorderFactory.createEmptyBorder(5, 20, 10, 20)));
        btnTabCapNhat.setForeground(new Color(0, 103, 192));
        btnTabDanhSach.setBorder(null);
        btnTabDanhSach.setForeground(new Color(177, 177, 177));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.first(jPanel1);
    }//GEN-LAST:event_btnTabCapNhatActionPerformed

    private void btnTabDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabDanhSachActionPerformed
        btnTabDanhSach.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 103, 192)),
                BorderFactory.createEmptyBorder(5, 20, 10, 20)));
        btnTabDanhSach.setForeground(new Color(0, 103, 192));
        btnTabCapNhat.setBorder(null);
        btnTabCapNhat.setForeground(new Color(177, 177, 177));
        CardLayout layout = (CardLayout) jPanel1.getLayout();
        layout.show(jPanel1, "card3");
    }//GEN-LAST:event_btnTabDanhSachActionPerformed

    private void btnVaoThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaoThiActionPerformed
        if (txtMaKT.getText().trim().equals("")) {
        } else {
            if (null == timKiemMatKhau(Integer.parseInt(txtMaKT.getText().trim()))) {
                int maKyThi = Integer.parseInt(txtMaKT.getText().trim());
                dispose();
                new QuizJDialog(maKyThi).setVisible(true);
            } else {
                switch (timKiemMatKhau(Integer.parseInt(txtMaKT.getText().trim())).trim()) {
                    case "" -> {
                        int maKyThi = Integer.parseInt(txtMaKT.getText().trim());
                        dispose();
                        new QuizJDialog(maKyThi).setVisible(true);
                    }
                    default -> {
                        if (timKiemMatKhau(Integer.parseInt(txtMaKT.getText().trim())) == null) {
                            int maKyThi = Integer.parseInt(txtMaKT.getText().trim());
                            dispose();
                            new QuizJDialog(maKyThi).setVisible(true);
                        } else {
                            String matKhau = JOptionPane.showInputDialog(this, "Nhập mật khẩu:", "Vào thi", JOptionPane.INFORMATION_MESSAGE);
                            if (matKhau == null) {
                            } else if (matKhau.equals(timKiemMatKhau(Integer.parseInt(txtMaKT.getText().trim())))) {
                                int maKyThi = Integer.parseInt(txtMaKT.getText().trim());
                                dispose();
                                new QuizJDialog(maKyThi).setVisible(true);
                            } else {
                                MsgBox.alert(this, "Mật khẩu đã nhập không đúng");

                            }

                        }
                    }
                }
            }

        }
    }//GEN-LAST:event_btnVaoThiActionPerformed

    private void txtMaKTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaKTFocusGained
        txtMaKT.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 103, 192)));
    }//GEN-LAST:event_txtMaKTFocusGained

    private void txtMaKTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaKTFocusLost
        txtMaKT.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(177, 177, 177)));
    }//GEN-LAST:event_txtMaKTFocusLost

    private void txtTenKHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKHFocusGained
        txtTenKH.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 103, 192)));
    }//GEN-LAST:event_txtTenKHFocusGained

    private void txtTenKHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKHFocusLost
        txtTenKH.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(177, 177, 177)));
    }//GEN-LAST:event_txtTenKHFocusLost

    private void txtTenKyThiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKyThiFocusGained
        txtTenKyThi.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 103, 192)));
    }//GEN-LAST:event_txtTenKyThiFocusGained

    private void txtTenKyThiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenKyThiFocusLost
        txtTenKyThi.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(177, 177, 177)));
    }//GEN-LAST:event_txtTenKyThiFocusLost

    private void txtThoiGianLamBaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThoiGianLamBaiFocusGained
        txtThoiGianLamBai.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(0, 103, 192)));
    }//GEN-LAST:event_txtThoiGianLamBaiFocusGained

    private void txtThoiGianLamBaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtThoiGianLamBaiFocusLost
        txtThoiGianLamBai.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(177, 177, 177)));
    }//GEN-LAST:event_txtThoiGianLamBaiFocusLost

    private void tblKyThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKyThiMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = tblKyThi.getSelectedRow();
            this.edit();
            btnTabCapNhat.doClick();
        }
    }//GEN-LAST:event_tblKyThiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThamGiaKyThiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThamGiaKyThiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThamGiaKyThiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThamGiaKyThiJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThamGiaKyThiJDialog dialog = new ThamGiaKyThiJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTabCapNhat;
    private javax.swing.JButton btnTabDanhSach;
    private javax.swing.JButton btnVaoThi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHocPhi;
    private javax.swing.JLabel lblMaCD;
    private javax.swing.JLabel lblTenCD;
    private javax.swing.JLabel lblThoiLuong;
    private javax.swing.JTable tblKyThi;
    private javax.swing.JTextField txtMaKT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenKyThi;
    private javax.swing.JTextField txtThoiGianLamBai;
    // End of variables declaration//GEN-END:variables
}
